language: ruby
cache:
  bundler: true
  directories:
  - node_modules
rvm:
- 2.3.0
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bin/rails db:environment:set
- npm install -g bower
- npm install
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: MMWKhBKeTT6iyu6AUlXxjYMoPLbv+/3IMxWz96N5rNGbOMY7V40CEY+q1oqWO1hps+x91cPEti0mwDFoPvAGy/9CDLYYMtZmBS2essWMQxKEbDh0w9HIg1/i1LRwfgxKJoBw4ZOQRguqtl+9dgoP+vwKGrLypjSs6+7+vzbOFb9YMvjimdkq9I7hY1ciQ9hDYs9UXjW33QrLewlqV76eRSAsNF13U+WIUoigK8Krdn84hDXEZ+4Cl1toDhjYsf8jKcv2i4JwbgQbl4gYl1tsSVHLMTRsWQxwkN45o2KTK3kJgkdxeJxadByPh0aRvKP7BWWu/P5dshqjsOZVeKbd+rMOHO4nmaSKwUQKSKSL3xVApoo3rY3i5dRoKAkoUM8tz314SlBsaDmCzx9heUm8wakl2Yeg1q1IHOuwGLFpxSc1y33oBjTsLzEgdIa3ndse3n282vZuc7CO06PsaNUf5s+U1SwZbcEWV4vHXipVkLKF+GLGjt6BI13fdFSCq1rUJPbupC0U9i+Rk40wkT2rSI2ZyAKv8FJR7KXKFWEYkQxdaNr2l51+/zpDDsg02+k02lPgPkEZjS8cNuKpYWAsVE8A+dLd40w7///oTgkEKSz4kNvJes8+QWSOgYFMADg6qrWGfUmn+lk7QW5FcaawWZ8WC+XlSSvvIIgvoJZmQpQ=
