language: ruby
cache:
  bundler: true
  directories:
  - node_modules
rvm:
- 2.3.0
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bin/rails db:environment:set
- npm install -g bower
- npm install
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: MMWKhBKeTT6iyu6AUlXxjYMoPLbv+/3IMxWz96N5rNGbOMY7V40CEY+q1oqWO1hps+x91cPEti0mwDFoPvAGy/9CDLYYMtZmBS2essWMQxKEbDh0w9HIg1/i1LRwfgxKJoBw4ZOQRguqtl+9dgoP+vwKGrLypjSs6+7+vzbOFb9YMvjimdkq9I7hY1ciQ9hDYs9UXjW33QrLewlqV76eRSAsNF13U+WIUoigK8Krdn84hDXEZ+4Cl1toDhjYsf8jKcv2i4JwbgQbl4gYl1tsSVHLMTRsWQxwkN45o2KTK3kJgkdxeJxadByPh0aRvKP7BWWu/P5dshqjsOZVeKbd+rMOHO4nmaSKwUQKSKSL3xVApoo3rY3i5dRoKAkoUM8tz314SlBsaDmCzx9heUm8wakl2Yeg1q1IHOuwGLFpxSc1y33oBjTsLzEgdIa3ndse3n282vZuc7CO06PsaNUf5s+U1SwZbcEWV4vHXipVkLKF+GLGjt6BI13fdFSCq1rUJPbupC0U9i+Rk40wkT2rSI2ZyAKv8FJR7KXKFWEYkQxdaNr2l51+/zpDDsg02+k02lPgPkEZjS8cNuKpYWAsVE8A+dLd40w7///oTgkEKSz4kNvJes8+QWSOgYFMADg6qrWGfUmn+lk7QW5FcaawWZ8WC+XlSSvvIIgvoJZmQpQ=
  run:
  - rake db:migrate
addons:
  code_climate:
    repo_token: 8f68f9372f018ddb25968ac0ecbc24d8ecc9f4455cee1880fd99e09d4f7c4bf1
notifications:
  slack:
    secure: vLgIDnS6QHvZdPyyXmB+ab3cnhvVPyt5Yb5l7R1w4rhWg5PYrNOQcjPbemBGZygqXJTyDgTOaJX2TZkMjNIW+4ViKKbElPOnX+GAhvC4pnLq/7QZhirZSvrp4L/fD5UXHZG+3Sa+eqLCxtBr+/XnU+WTNN0u/OjtMMmApHr+/bIXuqFIQAwhCUC8zImFl58jQ3yulGet/MbYsxqMjD061GftKK4WQxWB0d+hp38V0VyZNOulaA2Lq/bUXJVd5494+KT8jMxCxsVhg6V3gCE4glw5KcSWtZ+dET9NAD4Sgu35yP98oj/ym9nSjVjPAiXRZ5nLuiXo50+7ipRYPzknGKhGKyjl7eJNbE3Hzo9C3UCv8bt7ijODQZ6RultlWKb/4OdywNVUTpveEdQ5rsDSOViEgu0iYXLa3u1iyARBNedzpLiNhMTT6d1RkwG6Qd1nkwaAz0yJ91xvsMlzrZNr438xHLa1vrNstx2u/dYJpJNoJl/PzO1zZgQ6hIc7AUum33UOfdPVZE6I9QrFSItrK60LRHLhk/M8WTjQg4GdxJGsOZWeyCSJozSAr8ymwumTRJ3QwK/8pAHPNrybwFHk+reNic0AaQD0RBGA2JR78C03P3pFwdc8HzgBGK6hQV+oYi/zhW9rUT2fDKIqZeKn5I+xgP1EropCdYCncNSA9bg=
